// This file is automatically generated.
const int OPCODE_COUNT = 16;
enum class Opcode {
    END,
    EXIT,
    FADE,
    GOTO,
    IF,
    IFNOT,
    INPUT,
    MUSIC,
    RESET,
    RESPONSE,
    SAVE,
    SAY,
    SETPLAYER,
    SETVAR,
    SPAWN,
    SPRITE
};
