// This file is automatically generated.
const char OPCODE_NAMES[OPCODE_COUNT][16] = {
    "end",
    "exit",
    "fade",
    "goto",
    "input",
    "reset",
    "response",
    "save",
    "say",
    "spawn"
};
