// This file is automatically generated.
const char OPCODE_NAMES[OPCODE_COUNT][16] = {
    "end",
    "exit",
    "fade",
    "goto",
    "if",
    "ifnot",
    "input",
    "music",
    "reset",
    "response",
    "save",
    "say",
    "setplayer",
    "setvar",
    "spawn",
    "sprite"
};
