// This file is automatically generated.
const int SPRITE_COUNT = 16;
enum class Sprite {
    GIRL_BOT,
    GIRL_HEAD,
    GIRL_TOP,
    GOBLIN_BOT,
    GOBLIN_HEAD,
    GOBLIN_TOP,
    HERO_BOT,
    HERO_HEAD,
    HERO_TOP,
    ITEM_SWORD,
    SAGE1_BOT,
    SAGE1_HEAD,
    SAGE1_TOP,
    SAGE2_BOT,
    SAGE2_HEAD,
    SAGE2_TOP
};
