// This file is automatically generated.
const int SPRITE_COUNT = 8;
enum class Sprite {
    GIRL_HEAD,
    GOBLIN_BOT,
    GOBLIN_HEAD,
    GOBLIN_TOP,
    HERO_BOT,
    HERO_HEAD,
    HERO_TOP,
    MAGE_BOT
};
