// This file is automatically generated.
const int SPRITE_COUNT = 10;
enum class Sprite {
    GIRL_BOT,
    GIRL_HEAD,
    GIRL_TOP,
    GOBLIN_BOT,
    GOBLIN_HEAD,
    GOBLIN_TOP,
    HERO_BOT,
    HERO_HEAD,
    HERO_TOP,
    MAGE_BOT
};
