// This file is automatically generated.
const char SPRITE_NAMES[SPRITE_COUNT][16] = {
    "girl_bot",
    "girl_head",
    "girl_top",
    "goblin_bot",
    "goblin_head",
    "goblin_top",
    "hero_bot",
    "hero_head",
    "hero_top",
    "mage_bot"
};
